swagger: "2.0"
info:
  version: 1.0.0
  title: Swagger Customers
  description: A sample API that demonstrates Swagger Server features

host: customers.swagger.io:8000

consumes:
  - application/json
produces:
  - application/json

definitions:
  customer:
    type: object
    required:
      - name
    properties:
      id:
        type: integer
        format: int3
        primary: true
        autoincrement: true
      name:
        type: string
        minLength: 4
        pattern: "^[a-zA-Z0-9- ]+$"

parameters:
  customerId:
    name: customerId
    in: path
    description: Id of the customer
    required: true
    type: string
  pageSize:
    name: pageSize
    in: query
    description: Number of customers returned
    type: integer
  pageNumber:
    name: pageNumber
    in: query
    description: Page number
    type: integer

paths:
  /customers:
    get:
      description: Returns all customers
      operationId: findCustomers
      parameters:
        - $ref: "#/parameters/pageSize"
        - $ref: "#/parameters/pageNumber"
      responses:
        200:
          description: Returns the matching customers
          schema:
            type: array
            items:
              $ref: "#/definitions/customer"
          headers:
            last-modified:
              type: string
              description: The date/time that a pet was last modified

    post:
      description: Creates a new customer
      operationId: addCustomer
      parameters:
        - name: customer
          in: body
          description: The pet to add to the store
          required: true
          schema:
            $ref: "#/definitions/customer"
      responses:
        201:
          description: Returns the newly-added pet
          schema:
            $ref: "#/definitions/customer"
          headers:
            Location:
              type: string
              description: The URL of the newly-added pet

  /customers/{customerId}:
    parameters:
      - $ref: "#/parameters/customerId"

    get:
      description: Returns a customer by id
      operationId: findCustomerById
      responses:
        default:
          description: Returns the customer data
          schema:
            $ref: "#/definitions/customer"
          headers:
            last-modified:
              type: string
              description: The date/time that the pet was last modified

    patch:
      description: Updates a customer by id
      parameters:
        - name: customer
          in: body
          description: The updated pet info
          required: true
          schema:
            $ref: "#/definitions/customer"
      responses:
        default:
          description: Returns the updated pet data
          schema:
            $ref: "#/definitions/customer"

  /:
    get:
      produces:
        - text/html
      responses:
        default:
          description: The Swagger Pet Store homepage :)
          schema:
            type: file
            default:
              $ref: index.html
